### ISSUE TITLE
Implementation of handing taxation redistribution

### ISSUE THREAD

**Issue by zeckli** [thematters/contracts#124]
### Description
Create contract for handing on-chain taxation and redistribution.

### Todos
- [ ] Establish flow of moving taxation between contracts
- [ ] Implementation of taxation redistribution
- [ ] Withdrawal of funding
- [ ] Emit events

### Stories
- https://github.com/thematters/developer-resource/issues/352
